exclude:
- /client/src/assets/js/ie/.*
- /client/src/assets/js/.*
- /client/karma.conf.js
- /server/gruntfile.js
component_depth: 1
languages:
- name: go
  test:
    include:
    - .*_test\.go
- name: javascript
- name: script
- name: typescript
  test:
    include:
    - .*\.spec\.ts
    - .*api\.ts
    - .*test\.ts